import { PetSpeciesDefinition, PetSpeciesKey } from '../types/pet';

/**
 * Pet species configuration catalog.
 * Highly extensible architecture for virtual pets.
 */
export const PET_CATALOG: Record<PetSpeciesKey, PetSpeciesDefinition> = {
  fox: {
    type: 'fox',
    displayName: 'Zorro',
    speciesEmoji: '🦊',
    defaultName: 'Rocky',
    personality: 'molesto',
    description: 'Astuto, sarcástico y bromista, con pelaje anaranjado y cola esponjosa.',
    favoriteFood: 'Muslito de pollo crujiente',
    foodEmoji: '🍗',
    backgroundTheme: 'fox_forest',
    themeColor: {
      primary: '#ea580c',
      accent: '#fdba74',
      badgeBg: 'bg-orange-100 text-orange-800 border-orange-200',
      bubbleBg: 'bg-orange-50/90 border-orange-200',
      bgGradient: 'from-amber-100 via-orange-50 to-amber-200/80',
    },
    spriteSheet: '/sprites/fox.png',
  },
  turtle: {
    type: 'turtle',
    displayName: 'Tortuga',
    speciesEmoji: '🐢',
    defaultName: 'Donatello',
    personality: 'lenta',
    description: 'Pacífica, pensativa y paciente, con un caparazón protector y ojos brillantes.',
    favoriteFood: 'Hojas verdes frescas',
    foodEmoji: '🥬',
    backgroundTheme: 'turtle_zen',
    themeColor: {
      primary: '#16a34a',
      accent: '#86efac',
      badgeBg: 'bg-emerald-100 text-emerald-800 border-emerald-200',
      bubbleBg: 'bg-emerald-50/90 border-emerald-200',
      bgGradient: 'from-emerald-100 via-teal-50 to-emerald-200/80',
    },
    spriteSheet: '/sprites/turtle.png',
  },
  rabbit: {
    type: 'rabbit',
    displayName: 'Conejo',
    speciesEmoji: '🐰',
    defaultName: 'Copito',
    personality: 'apurado',
    description: 'Hiperactivo, saltarín y siempre apurado con orejitas rosadas.',
    favoriteFood: 'Zanahoria crujiente',
    foodEmoji: '🥕',
    backgroundTheme: 'rabbit_meadow',
    themeColor: {
      primary: '#9333ea',
      accent: '#d8b4fe',
      badgeBg: 'bg-purple-100 text-purple-800 border-purple-200',
      bubbleBg: 'bg-purple-50/90 border-purple-200',
      bgGradient: 'from-fuchsia-100 via-purple-50 to-pink-200/80',
    },
    spriteSheet: '/sprites/rabbit.png',
  },
  panda: {
    type: 'panda',
    displayName: 'Panda',
    speciesEmoji: '🐼',
    defaultName: 'Bao Bao',
    personality: 'tierno',
    description: 'Tierno, bonachón y comilón, experto en rodar por la hierba.',
    favoriteFood: 'Brote de bambú tierno',
    foodEmoji: '🎋',
    backgroundTheme: 'panda_bamboo',
    themeColor: {
      primary: '#334155',
      accent: '#cbd5e1',
      badgeBg: 'bg-slate-100 text-slate-800 border-slate-200',
      bubbleBg: 'bg-slate-50/90 border-slate-200',
      bgGradient: 'from-emerald-100 via-slate-50 to-teal-100/90',
    },
    spriteSheet: '/sprites/panda.png',
  },
  fish: {
    type: 'fish',
    displayName: 'Pez Dorado',
    speciesEmoji: '🐟',
    defaultName: 'Burbujas',
    personality: 'curioso',
    description: 'Curioso, distraído y alegre nadando en su pecera mágica.',
    favoriteFood: 'Bolitas de hojuelas doradas',
    foodEmoji: '🫧',
    backgroundTheme: 'fish_ocean',
    themeColor: {
      primary: '#0284c7',
      accent: '#7dd3fc',
      badgeBg: 'bg-sky-100 text-sky-800 border-sky-200',
      bubbleBg: 'bg-sky-50/90 border-sky-200',
      bgGradient: 'from-cyan-100 via-sky-50 to-blue-200/80',
    },
    spriteSheet: '/sprites/fish.png',
  },
  koala: {
    type: 'koala',
    displayName: 'Koala',
    speciesEmoji: '🐨',
    defaultName: 'Koko',
    personality: 'dormilon',
    description: 'Dormilón, abrazador y amante de las siestas colgado de su ramita.',
    favoriteFood: 'Ramitas de eucalipto dulce',
    foodEmoji: '🌿',
    backgroundTheme: 'koala_eucalyptus',
    themeColor: {
      primary: '#475569',
      accent: '#94a3b8',
      badgeBg: 'bg-zinc-100 text-zinc-800 border-zinc-200',
      bubbleBg: 'bg-zinc-50/90 border-zinc-200',
      bgGradient: 'from-lime-100 via-emerald-50 to-green-200/80',
    },
    spriteSheet: '/sprites/koala.png',
  },
  raccoon: {
    type: 'raccoon',
    displayName: 'Mapachito',
    speciesEmoji: '🦝',
    defaultName: 'Bandit',
    personality: 'picaro',
    description: 'Pícaro investigador con antifaz natural y manos lavadoras.',
    favoriteFood: 'Manzana jugosa',
    foodEmoji: '🍎',
    backgroundTheme: 'raccoon_night',
    themeColor: {
      primary: '#52525b',
      accent: '#a1a1aa',
      badgeBg: 'bg-neutral-100 text-neutral-800 border-neutral-200',
      bubbleBg: 'bg-neutral-50/90 border-neutral-200',
      bgGradient: 'from-indigo-100 via-slate-50 to-violet-200/80',
    },
    spriteSheet: '/sprites/raccoon.png',
  },
  red_panda: {
    type: 'red_panda',
    displayName: 'Panda Rojo',
    speciesEmoji: '🐾',
    defaultName: 'Rory',
    personality: 'tierno',
    description: 'Adorable bola de pelo rojizo con cola rayada y orejitas esponjosas.',
    favoriteFood: 'Bambú con bayas silvestres',
    foodEmoji: '🍓',
    backgroundTheme: 'redpanda_cherry',
    themeColor: {
      primary: '#c2410c',
      accent: '#fdba74',
      badgeBg: 'bg-orange-100 text-orange-800 border-orange-200',
      bubbleBg: 'bg-orange-50/90 border-orange-200',
      bgGradient: 'from-rose-100 via-orange-50 to-amber-200/80',
    },
    spriteSheet: '/sprites/red_panda.png',
  },
  dragon: {
    type: 'dragon',
    displayName: 'Dragoncito',
    speciesEmoji: '🐉',
    defaultName: 'Ignis',
    personality: 'jugueton',
    description: 'Valiente, chispeante y lanzador de pequeñas chispas de felicidad.',
    favoriteFood: 'Fruta volcánica asada',
    foodEmoji: '🔥',
    backgroundTheme: 'dragon_cavern',
    themeColor: {
      primary: '#dc2626',
      accent: '#fca5a5',
      badgeBg: 'bg-red-100 text-red-800 border-red-200',
      bubbleBg: 'bg-red-50/90 border-red-200',
      bgGradient: 'from-red-100 via-amber-50 to-orange-200/80',
    },
    spriteSheet: '/sprites/dragon.png',
  },
  cat: {
    type: 'cat',
    displayName: 'Gatito',
    speciesEmoji: '🐱',
    defaultName: 'Michi',
    personality: 'molesto',
    description: 'Elegante, curioso y con un ronroneo que derrite a cualquiera.',
    favoriteFood: 'Pescadito fresco',
    foodEmoji: '🐟',
    backgroundTheme: 'cat_room',
    themeColor: {
      primary: '#f59e0b',
      accent: '#fde68a',
      badgeBg: 'bg-amber-100 text-amber-800 border-amber-200',
      bubbleBg: 'bg-amber-50/90 border-amber-200',
      bgGradient: 'from-amber-100 via-yellow-50 to-orange-100/80',
    },
    spriteSheet: '/sprites/cat.png',
  },
  dog: {
    type: 'dog',
    displayName: 'Perrito',
    speciesEmoji: '🐶',
    defaultName: 'Toby',
    personality: 'jugueton',
    description: 'Super fiel, alegre y siempre moviendo la colita con entusiasmo.',
    favoriteFood: 'Galletita de huesito',
    foodEmoji: '🦴',
    backgroundTheme: 'dog_park',
    themeColor: {
      primary: '#d97706',
      accent: '#fde68a',
      badgeBg: 'bg-yellow-100 text-yellow-800 border-yellow-200',
      bubbleBg: 'bg-yellow-50/90 border-yellow-200',
      bgGradient: 'from-yellow-100 via-emerald-50 to-green-100/80',
    },
    spriteSheet: '/sprites/dog.png',
  },
  monkey: {
    type: 'monkey',
    displayName: 'Monito',
    speciesEmoji: '🐵',
    defaultName: 'Coco',
    personality: 'jugueton',
    description: 'Acróbata simpático, risueño y fanático de las bananas.',
    favoriteFood: 'Banana madura',
    foodEmoji: '🍌',
    backgroundTheme: 'monkey_jungle',
    themeColor: {
      primary: '#b45309',
      accent: '#fcd34d',
      badgeBg: 'bg-amber-100 text-amber-800 border-amber-200',
      bubbleBg: 'bg-amber-50/90 border-amber-200',
      bgGradient: 'from-yellow-100 via-lime-50 to-emerald-200/80',
    },
    spriteSheet: '/sprites/monkey.png',
  },
  penguin: {
    type: 'penguin',
    displayName: 'Pingüinito',
    speciesEmoji: '🐧',
    defaultName: 'Pipo',
    personality: 'tierno',
    description: 'Deslizador sobre el hielo con bufanda imaginaria y paso tierno.',
    favoriteFood: 'Pescadito helado',
    foodEmoji: '🐟',
    backgroundTheme: 'penguin_arctic',
    themeColor: {
      primary: '#0891b2',
      accent: '#a5f3fc',
      badgeBg: 'bg-cyan-100 text-cyan-800 border-cyan-200',
      bubbleBg: 'bg-cyan-50/90 border-cyan-200',
      bgGradient: 'from-sky-100 via-cyan-50 to-indigo-100/80',
    },
    spriteSheet: '/sprites/penguin.png',
  },
  squirrel: {
    type: 'squirrel',
    displayName: 'Ardillita',
    speciesEmoji: '🐿️',
    defaultName: 'Nuez',
    personality: 'apurado',
    description: 'Guardiana de bellotas, rápida trepadora de copas de árboles.',
    favoriteFood: 'Bellota dorada',
    foodEmoji: '🌰',
    backgroundTheme: 'squirrel_autumn',
    themeColor: {
      primary: '#a16207',
      accent: '#fde047',
      badgeBg: 'bg-yellow-100 text-yellow-800 border-yellow-200',
      bubbleBg: 'bg-yellow-50/90 border-yellow-200',
      bgGradient: 'from-amber-100 via-orange-50 to-yellow-200/80',
    },
    spriteSheet: '/sprites/squirrel.png',
  },
  frog: {
    type: 'frog',
    displayName: 'Rana',
    speciesEmoji: '🐸',
    defaultName: 'Sapo',
    personality: 'jugueton',
    description: 'Saltarina de hojas de loto que canta con voz graciosa.',
    favoriteFood: 'Mosquitos de azúcar',
    foodEmoji: '🪰',
    backgroundTheme: 'frog_pond',
    themeColor: {
      primary: '#15803d',
      accent: '#86efac',
      badgeBg: 'bg-green-100 text-green-800 border-green-200',
      bubbleBg: 'bg-green-50/90 border-green-200',
      bgGradient: 'from-emerald-100 via-teal-50 to-green-200/80',
    },
    spriteSheet: '/sprites/frog.png',
  },
  hamster: {
    type: 'hamster',
    displayName: 'Hámster',
    speciesEmoji: '🐹',
    defaultName: 'Mochi',
    personality: 'tierno',
    description: 'Bolas de mofletes llenos de semillas con pasos chiquitos.',
    favoriteFood: 'Semillas de girasol',
    foodEmoji: '🌻',
    backgroundTheme: 'hamster_cozy',
    themeColor: {
      primary: '#ea580c',
      accent: '#fed7aa',
      badgeBg: 'bg-amber-100 text-amber-800 border-amber-200',
      bubbleBg: 'bg-amber-50/90 border-amber-200',
      bgGradient: 'from-amber-100 via-yellow-50 to-orange-100/80',
    },
    spriteSheet: '/sprites/hamster.png',
  },
  lion: {
    type: 'lion',
    displayName: 'Leoncito',
    speciesEmoji: '🦁',
    defaultName: 'Simba',
    personality: 'jugueton',
    description: 'Pequeño rey de la sabana con melena suave y rugido tierno.',
    favoriteFood: 'Filetito jugoso',
    foodEmoji: '🥩',
    backgroundTheme: 'lion_savanna',
    themeColor: {
      primary: '#ca8a04',
      accent: '#fef08a',
      badgeBg: 'bg-yellow-100 text-yellow-800 border-yellow-200',
      bubbleBg: 'bg-yellow-50/90 border-yellow-200',
      bgGradient: 'from-amber-100 via-yellow-50 to-orange-200/80',
    },
    spriteSheet: '/sprites/lion.png',
  },
  tiger: {
    type: 'tiger',
    displayName: 'Tigrecito',
    speciesEmoji: '🐯',
    defaultName: 'Tigro',
    personality: 'picaro',
    description: 'Rayas elegantes, sigiloso y amante de los saltos sorpresa.',
    favoriteFood: 'Bocado de la selva',
    foodEmoji: '🍖',
    backgroundTheme: 'tiger_jungle',
    themeColor: {
      primary: '#ea580c',
      accent: '#fdba74',
      badgeBg: 'bg-orange-100 text-orange-800 border-orange-200',
      bubbleBg: 'bg-orange-50/90 border-orange-200',
      bgGradient: 'from-orange-100 via-amber-50 to-emerald-100/80',
    },
    spriteSheet: '/sprites/tiger.png',
  },
  owl: {
    type: 'owl',
    displayName: 'Búho',
    speciesEmoji: '🦉',
    defaultName: 'Sabio',
    personality: 'lenta',
    description: 'Ojos gigantes que miran la noche estrellada con gran sabiduría.',
    favoriteFood: 'Bayas nocturnas',
    foodEmoji: '🫐',
    backgroundTheme: 'owl_night',
    themeColor: {
      primary: '#6366f1',
      accent: '#c7d2fe',
      badgeBg: 'bg-indigo-100 text-indigo-800 border-indigo-200',
      bubbleBg: 'bg-indigo-50/90 border-indigo-200',
      bgGradient: 'from-indigo-100 via-slate-50 to-purple-200/80',
    },
    spriteSheet: '/sprites/owl.png',
  },
  bear: {
    type: 'bear',
    displayName: 'Osito',
    speciesEmoji: '🐻',
    defaultName: 'Miel',
    personality: 'dormilon',
    description: 'Abrazos acolchados de oso y afición interminable por la miel.',
    favoriteFood: 'Tarro de miel dulce',
    foodEmoji: '🍯',
    backgroundTheme: 'bear_woods',
    themeColor: {
      primary: '#78350f',
      accent: '#fde68a',
      badgeBg: 'bg-amber-100 text-amber-800 border-amber-200',
      bubbleBg: 'bg-amber-50/90 border-amber-200',
      bgGradient: 'from-amber-100 via-emerald-50 to-lime-100/80',
    },
    spriteSheet: '/sprites/bear.png',
  },
  unicorn: {
    type: 'unicorn',
    displayName: 'Unicornio',
    speciesEmoji: '🦄',
    defaultName: 'Estrella',
    personality: 'tierno',
    description: 'Cuerno reluciente de arcoíris y crin de nubes mágicas.',
    favoriteFood: 'Caramelo de nube de algodón',
    foodEmoji: '🧁',
    backgroundTheme: 'unicorn_rainbow',
    themeColor: {
      primary: '#ec4899',
      accent: '#fbcfe8',
      badgeBg: 'bg-pink-100 text-pink-800 border-pink-200',
      bubbleBg: 'bg-pink-50/90 border-pink-200',
      bgGradient: 'from-pink-100 via-purple-50 to-sky-100/90',
    },
    spriteSheet: '/sprites/unicorn.png',
  },
};

export const INITIAL_AVAILABLE_SPECIES: PetSpeciesKey[] = [
  'fox',
  'turtle',
  'rabbit',
  'panda',
  'fish',
  'koala',
  'raccoon',
  'red_panda',
  'dragon',
  'cat',
  'dog',
  'monkey',
  'penguin',
  'squirrel',
  'frog',
  'hamster',
  'lion',
  'tiger',
  'owl',
  'bear',
  'unicorn',
];

export function getPetSpecies(type: string): PetSpeciesDefinition {
  const key = type as PetSpeciesKey;
  return PET_CATALOG[key] || PET_CATALOG.fox;
}
