import { PetSpeciesDefinition, PetSpeciesKey } from '../types/pet';

/**
 * Canonical pet catalog.
 *
 * IMPORTANT:
 * - Every entry below maps to a real sprite sheet in /public/sprites/.
 * - Do not add a species without a real supplied sprite.
 * - Sprite filenames are intentionally short and stable.
 */
export const PET_CATALOG: Record<PetSpeciesKey, PetSpeciesDefinition> = {
  fox: {
    type: 'fox',
    displayName: 'Zorro',
    speciesEmoji: '🦊',
    defaultName: 'Rocky',
    personality: 'molesto',
    description: 'Astuto, sarcástico y bromista.',
    favoriteFood: 'Muslito de pollo',
    foodEmoji: '🍗',
    backgroundTheme: 'fox_forest',
    themeColor: { primary: '#ea580c', accent: '#fdba74', badgeBg: 'bg-orange-100 text-orange-800 border-orange-200', bubbleBg: 'bg-orange-50/90 border-orange-200', bgGradient: 'from-amber-100 via-orange-50 to-amber-200/80' },
    spriteSheet: '/sprites/fox.png',
  },
  turtle: {
    type: 'turtle',
    displayName: 'Tortuga',
    speciesEmoji: '🐢',
    defaultName: 'Donatello',
    personality: 'lenta',
    description: 'Pacífica, pensativa y paciente.',
    favoriteFood: 'Hojas verdes',
    foodEmoji: '🥬',
    backgroundTheme: 'turtle_zen',
    themeColor: { primary: '#16a34a', accent: '#86efac', badgeBg: 'bg-emerald-100 text-emerald-800 border-emerald-200', bubbleBg: 'bg-emerald-50/90 border-emerald-200', bgGradient: 'from-emerald-100 via-teal-50 to-emerald-200/80' },
    spriteSheet: '/sprites/turtle.png',
  },
  raccoon: {
    type: 'raccoon',
    displayName: 'Mapache',
    speciesEmoji: '🦝',
    defaultName: 'Bandit',
    personality: 'picaro',
    description: 'Curioso, pícaro y siempre investigando.',
    favoriteFood: 'Manzana',
    foodEmoji: '🍎',
    backgroundTheme: 'raccoon_night',
    themeColor: { primary: '#52525b', accent: '#a1a1aa', badgeBg: 'bg-neutral-100 text-neutral-800 border-neutral-200', bubbleBg: 'bg-neutral-50/90 border-neutral-200', bgGradient: 'from-indigo-100 via-slate-50 to-violet-200/80' },
    spriteSheet: '/sprites/raccoon.png',
  },
  red_panda: {
    type: 'red_panda',
    displayName: 'Panda rojo',
    speciesEmoji: '🐾',
    defaultName: 'Rory',
    personality: 'tierno',
    description: 'Tierno, tranquilo y muy cariñoso.',
    favoriteFood: 'Bambú con bayas',
    foodEmoji: '🍓',
    backgroundTheme: 'redpanda_cherry',
    themeColor: { primary: '#c2410c', accent: '#fdba74', badgeBg: 'bg-orange-100 text-orange-800 border-orange-200', bubbleBg: 'bg-orange-50/90 border-orange-200', bgGradient: 'from-rose-100 via-orange-50 to-amber-200/80' },
    spriteSheet: '/sprites/red_panda.png',
  },
  squirrel: {
    type: 'squirrel',
    displayName: 'Ardilla',
    speciesEmoji: '🐿️',
    defaultName: 'Nuez',
    personality: 'curioso',
    description: 'Curiosa, inquieta y amante de las aventuras.',
    favoriteFood: 'Nueces',
    foodEmoji: '🌰',
    backgroundTheme: 'forest',
    themeColor: { primary: '#a16207', accent: '#facc15', badgeBg: 'bg-yellow-100 text-yellow-800 border-yellow-200', bubbleBg: 'bg-yellow-50/90 border-yellow-200', bgGradient: 'from-yellow-100 via-amber-50 to-orange-100' },
    spriteSheet: '/sprites/squirrel.png',
  },
  monkey: {
    type: 'monkey',
    displayName: 'Mono',
    speciesEmoji: '🐒',
    defaultName: 'Milo',
    personality: 'jugueton',
    description: 'Juguetón, divertido y siempre listo para bailar.',
    favoriteFood: 'Plátano',
    foodEmoji: '🍌',
    backgroundTheme: 'jungle',
    themeColor: { primary: '#92400e', accent: '#f59e0b', badgeBg: 'bg-amber-100 text-amber-800 border-amber-200', bubbleBg: 'bg-amber-50/90 border-amber-200', bgGradient: 'from-amber-100 via-yellow-50 to-orange-100' },
    spriteSheet: '/sprites/monkey.png',
  },
  penguin: {
    type: 'penguin',
    displayName: 'Pingüino',
    speciesEmoji: '🐧',
    defaultName: 'Pipo',
    personality: 'tierno',
    description: 'Tierno, alegre y un poquito travieso.',
    favoriteFood: 'Pescado',
    foodEmoji: '🐟',
    backgroundTheme: 'ice',
    themeColor: { primary: '#2563eb', accent: '#93c5fd', badgeBg: 'bg-blue-100 text-blue-800 border-blue-200', bubbleBg: 'bg-blue-50/90 border-blue-200', bgGradient: 'from-sky-100 via-white to-blue-100' },
    spriteSheet: '/sprites/penguin.png',
  },
  panda: {
    type: 'panda',
    displayName: 'Panda',
    speciesEmoji: '🐼',
    defaultName: 'Bambú',
    personality: 'tierno',
    description: 'Cariñoso, tranquilo y amante de las siestas.',
    favoriteFood: 'Bambú',
    foodEmoji: '🎋',
    backgroundTheme: 'bamboo',
    themeColor: { primary: '#166534', accent: '#86efac', badgeBg: 'bg-green-100 text-green-800 border-green-200', bubbleBg: 'bg-green-50/90 border-green-200', bgGradient: 'from-green-100 via-emerald-50 to-lime-100' },
    spriteSheet: '/sprites/panda.png',
  },
  fish: {
    type: 'fish',
    displayName: 'Pez',
    speciesEmoji: '🐟',
    defaultName: 'Burbuja',
    personality: 'curioso',
    description: 'Curioso, distraído y feliz entre burbujas.',
    favoriteFood: 'Hojuelas',
    foodEmoji: '🐠',
    backgroundTheme: 'aquarium',
    themeColor: { primary: '#0891b2', accent: '#67e8f9', badgeBg: 'bg-cyan-100 text-cyan-800 border-cyan-200', bubbleBg: 'bg-cyan-50/90 border-cyan-200', bgGradient: 'from-cyan-100 via-sky-50 to-blue-100' },
    spriteSheet: '/sprites/fish.png',
  },
  dragon: {
    type: 'dragon',
    displayName: 'Dragón',
    speciesEmoji: '🐉',
    defaultName: 'Draco',
    personality: 'jugueton',
    description: 'Pequeño dragón juguetón con mucha imaginación.',
    favoriteFood: 'Fruta dulce',
    foodEmoji: '🍓',
    backgroundTheme: 'dragon',
    themeColor: { primary: '#7c3aed', accent: '#c4b5fd', badgeBg: 'bg-violet-100 text-violet-800 border-violet-200', bubbleBg: 'bg-violet-50/90 border-violet-200', bgGradient: 'from-violet-100 via-fuchsia-50 to-purple-100' },
    spriteSheet: '/sprites/dragon.png',
  },
  cat: {
    type: 'cat',
    displayName: 'Gato',
    speciesEmoji: '🐱',
    defaultName: 'Michi',
    personality: 'tierno',
    description: 'Cariñoso, curioso y un poquito independiente.',
    favoriteFood: 'Pescado',
    foodEmoji: '🐟',
    backgroundTheme: 'garden',
    themeColor: { primary: '#db2777', accent: '#f9a8d4', badgeBg: 'bg-pink-100 text-pink-800 border-pink-200', bubbleBg: 'bg-pink-50/90 border-pink-200', bgGradient: 'from-pink-100 via-rose-50 to-fuchsia-100' },
    spriteSheet: '/sprites/cat.png',
  },
  koala: {
    type: 'koala',
    displayName: 'Koala',
    speciesEmoji: '🐨',
    defaultName: 'Koko',
    personality: 'dormilon',
    description: 'Tranquilo, dormilón y muy cariñoso.',
    favoriteFood: 'Eucalipto',
    foodEmoji: '🌿',
    backgroundTheme: 'eucalyptus',
    themeColor: { primary: '#65a30d', accent: '#bef264', badgeBg: 'bg-lime-100 text-lime-800 border-lime-200', bubbleBg: 'bg-lime-50/90 border-lime-200', bgGradient: 'from-lime-100 via-green-50 to-emerald-100' },
    spriteSheet: '/sprites/koala.png',
  },
};

export const INITIAL_AVAILABLE_SPECIES: PetSpeciesKey[] = [
  'fox',
  'turtle',
  'raccoon',
  'red_panda',
  'squirrel',
  'monkey',
  'penguin',
  'panda',
  'fish',
  'dragon',
  'cat',
  'koala',
];

const SPECIES_ALIASES: Record<string, PetSpeciesKey> = {
  fox: 'fox', zorro: 'fox', rocky: 'fox',
  turtle: 'turtle', tortuga: 'turtle', donatello: 'turtle',
  raccoon: 'raccoon', mapache: 'raccoon', mapachito: 'raccoon', bandit: 'raccoon',
  red_panda: 'red_panda', panda_rojo: 'red_panda', pandarojo: 'red_panda', rory: 'red_panda',
  squirrel: 'squirrel', ardilla: 'squirrel', nuez: 'squirrel',
  monkey: 'monkey', mono: 'monkey', milo: 'monkey',
  penguin: 'penguin', pinguino: 'penguin', pingüino: 'penguin', pipo: 'penguin',
  panda: 'panda', bambu: 'panda', bambú: 'panda',
  fish: 'fish', pez: 'fish', burbuja: 'fish',
  dragon: 'dragon', dragón: 'dragon', draco: 'dragon',
  cat: 'cat', gato: 'cat', michi: 'cat',
  koala: 'koala', koko: 'koala',
};

export function getPetSpecies(type: string | undefined | null): PetSpeciesDefinition {
  if (!type) return PET_CATALOG.fox;
  const normalizedKey = type.toLowerCase().trim();
  const canonicalKey = SPECIES_ALIASES[normalizedKey] || (normalizedKey as PetSpeciesKey);
  return PET_CATALOG[canonicalKey] || PET_CATALOG.fox;
}
